"""PPTX renderer — produces a real PowerPoint deck via python-pptx.

Per ADR-016. We have working precedent for python-pptx in this session
(used for the executive brief). This wraps it in the Renderer Protocol.
"""
from __future__ import annotations
import io
import logging
from pathlib import Path
from ._base import BaseRenderer

log = logging.getLogger(__name__)


class PptxRenderer(BaseRenderer):
    name = "pptx"
    output_extension = ".pptx"

    def render(self, data: dict, template: str | Path | None = None) -> bytes:
        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt
            from pptx.dml.color import RGBColor
        except ImportError:
            log.warning("python-pptx not installed; producing placeholder bytes")
            return self._stub_bytes(data)

        # Start from template if given, else blank widescreen
        if template and Path(template).exists():
            prs = Presentation(str(template))
        else:
            prs = Presentation()
            prs.slide_width = Inches(13.333)
            prs.slide_height = Inches(7.5)

        # Title slide
        title_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_layout)
        if slide.shapes.title:
            slide.shapes.title.text = data.get("title", "Generated by Knowledge Builder Framework")
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = data.get("subtitle", "")

        # Content slides — one per section
        for section_name, body in data.get("sections", {}).items():
            content_layout = prs.slide_layouts[1] if len(prs.slide_layouts) > 1 else prs.slide_layouts[0]
            slide = prs.slides.add_slide(content_layout)
            if slide.shapes.title:
                slide.shapes.title.text = section_name
            # Body
            tf = None
            for ph in slide.placeholders:
                if ph.placeholder_format.idx in (1, 2):
                    tf = ph.text_frame
                    break
            if tf is None:
                continue
            tf.clear()
            if isinstance(body, list):
                for i, item in enumerate(body):
                    p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
                    p.text = f"• {item}"
            elif isinstance(body, dict):
                first = True
                for k, v in body.items():
                    p = tf.paragraphs[0] if first else tf.add_paragraph()
                    p.text = f"• {k}: {v}"
                    first = False
            else:
                tf.text = str(body)

        buf = io.BytesIO()
        prs.save(buf)
        return buf.getvalue()

    @staticmethod
    def _stub_bytes(data: dict) -> bytes:
        # When python-pptx isn't installed, emit a tiny "manifest" so downstream
        # delivery can still happen — useful for shape-testing the pipeline.
        import json
        return ("STUB PPTX (install python-pptx to render real)\n" +
                json.dumps(data, indent=2, default=str)).encode("utf-8")
