"""gold_seed — bootstrap evaluation gold sets from example artifacts.

Per ADR-015 §Artifact families. Seeds extraction-gold and workflow-output-gold
JSONL files from an example artifact analyzed during the skill-builder session.
In stub mode no LLM is involved; gold entries are populated from the example
fields supplied by the persona team.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path


def seed_gold_set(
    persona: str,
    kb_name: str,
    artifact_path: str,
    extracted_fields: dict,
) -> list[dict]:
    """Create initial gold-set entries for the extraction skill.

    Args:
        persona: persona id (e.g. "tpm").
        kb_name: KB name short form (e.g. "weekly_project_status").
        artifact_path: path to the example artifact; used only as a citation.
        extracted_fields: dict of field_name → example_value from the persona
                          team's example outcome.  Used to populate the gold entry.

    Returns:
        A list of JSONL-ready dicts (one per synthesized gold entry).  Caller
        writes these to eval/gold_sets/{persona}-{kb_name}-extraction.jsonl.
    """
    if not extracted_fields:
        return [_empty_starter(persona, kb_name, artifact_path)]

    entry_id = f"ext-{_short_hash(persona + kb_name + artifact_path)}"

    entry = {
        "id": entry_id,
        "persona": persona,
        "kb": f"{persona}.{kb_name}",
        "source_citation": artifact_path,
        "input_description": (
            "Example outcome provided by persona team during skill-builder session. "
            "Replace source_citation with a real source URL before promoting."
        ),
        "expected_extraction": extracted_fields,
        "must_match_fields": list(extracted_fields.keys())[:5],
        "notes": "STARTER — generated by skill_builder gold_seed. Validate and expand.",
    }
    return [entry]


def seed_workflow_gold(
    persona: str,
    skill_name: str,
    task_description: str,
    example_fields: dict,
) -> list[dict]:
    """Create an initial workflow-output gold entry.

    Separate from seed_gold_set; used for workflow skill eval.
    """
    entry_id = f"wf-{_short_hash(persona + skill_name)}"
    return [
        {
            "id": entry_id,
            "persona": persona,
            "skill": skill_name,
            "question": task_description,
            "expected_skill": skill_name,
            "expected_output_includes": list(example_fields.keys())[:5],
            "min_intent_match_score": 0.85,
            "min_field_accuracy": 0.85,
            "notes": "STARTER — generated by skill_builder gold_seed. Validate and expand.",
        }
    ]


def entries_to_jsonl(entries: list[dict]) -> str:
    return "\n".join(json.dumps(e) for e in entries) + "\n"


# ---------------------------------------------------------------------------
# private helpers
# ---------------------------------------------------------------------------

def _empty_starter(persona: str, kb_name: str, artifact_path: str) -> dict:
    return {
        "id": "ext-001",
        "persona": persona,
        "kb": f"{persona}.{kb_name}",
        "source_citation": artifact_path or "REPLACE_WITH_REAL_SOURCE",
        "input_description": "REPLACE with a real source document excerpt.",
        "expected_extraction": {},
        "must_match_fields": [],
        "notes": "STARTER — no example fields were provided. Add real pairs.",
    }


def _short_hash(text: str) -> str:
    return hashlib.sha1(text.encode()).hexdigest()[:8]
